all:
	@make default
	@make debug
	@make pretty
	@make pretty-debug

default:
	go run main.go

debug:
	go run main.go -debug

pretty:
	go run main.go -pretty

pretty-debug:
	go run main.go -pretty -debug
