download-data:
	mkdir -p ./data
	curl -s https://www.randomlists.com/data/names-male.json -o ./data/names-male.json
	curl -s https://www.randomlists.com/data/names-female.json -o ./data/names-female.json
	curl -s https://www.randomlists.com/data/names-surnames.json -o ./data/names-surnames.json
